"id": issue.get("id"),
                    "number": issue.get("number"),
                    "title": issue.get("title"),
                    "assignees": [assignee.get("id") for assignee in issue.get("assignees", [])],
                    "state": issue.get("state"),
                    "created_at": issue.get("created_at"),
                    "closed_at": issue.get("closed_at"),
                    "comments": issue.get("comments"),
                    "labels": [label.get("name") for label in issue.get("labels", [])],
                    "body": issue.get("body")